// Core
import '../src/components/core/ArticleAuthor/stories';
import '../src/components/core/Button/stories';
import '../src/components/core/Collapsible/stories';
import '../src/components/core/Checkbox/stories';
import '../src/components/core/Datepicker/stories';
import '../src/components/core/Dropdown/stories';
import '../src/components/core/FileInput/stories';
import '../src/components/core/IconButton/stories';
import '../src/components/core/Image/stories';
import '../src/components/core/Input/stories';
import '../src/components/core/Label/stories';
import '../src/components/core/FormLogin/stories';
import '../src/components/core/Picture/stories';
import '../src/components/core/Template/stories';
import '../src/components/core/SVG/stories';
import '../src/components/core/Switch/stories';
import '../src/components/core/Tabs/stories';
import '../src/components/core/Tags/stories';
import '../src/components/core/TitleArticle/stories';
import '../src/components/core/PublishedBox/stories';
import '../src/components/core/HeaderArticle/stories';
import '../src/components/core/FooterArticle/stories';

// Views
import '../src/components/views/CreateNew/stories';
import '../src/components/views/DayMenu/stories';
import '../src/components/views/BodyArticle/stories';
import '../src/components/views/Article/stories';
